

[template]
cargo_generate_version = ">=0.22.0"
exclude = [
".git/",
"Cargo.lock",
"**/.env*",
"**/*.log",
"**/no_sync/**",
"**/no-sync/**",
"**/nosync/**",
".output/**",
".output/logging/**",
".output/profiling/**",
"debug/",
"target/",
"target_ra/",
"target_wasm/",
"dist/",
".lycheecache",
"debug/",
"target/",
"**/*.rs.bk",
"*.pdb",
".DS_Store",]

include = [
"!**.gitkeep",
"!.output/logging/",
"!.output/profiling/",]

[placeholders.github_username]
prompt = "Enter your name"
# choices = ["Alice", "Bob"]
# default = "Alice"
# regex filter: alphanumeric+underscore, alphatostart
regex = "^([a-z]|[A-Z])([a-z]|[A-Z]|[0-9]|[_])*$"
type = "string" # string, text, editor, bool
