[placeholders.github_username]
prompt = "Enter your GitHub username"
# choices = ["Alice", "Bob"]
# default = "Alice"
# regex filter: alphanumeric+underscore, alphatostart
regex = "^([a-z]|[A-Z])([a-z]|[A-Z]|[0-9]|[_])*$"
type = "string"
# string, text, editor, bool
