# rust-toolchain
# link describing options for this file: https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

[toolchain]
channel = "nightly"
targets = [ "wasm32-unknown-unknown" ]
components = [ "rustfmt", "clippy" ]

# [toolchain]
# channel = "1.81"  # Avoid specifying a patch version here; see https://github.com/emilk/eframe_template/issues/145
# components = [ "rustfmt", "clippy" ]
# targets = [ "wasm32-unknown-unknown" ]
